import Friends from "@/assets/logo/friends.svg";
import Memory from "@/assets/logo/memory.svg";
import IconFriends from "@/assets/logo/icon_friends.svg";
import IconMemory from "@/assets/logo/icon_memory.svg";
import Banner from "@/assets/talents/banner.png";

export const projects = [
  {
    title: "Sahari Friends",
    description:
      "enjoy a safe and comfortable social experience without the risk of negative exploitation.",
    link: "/friends",
    image: Friends,
    icon: IconFriends,
  },
  {
    title: "Sahari Memory",
    description:
      "allows users to interact with an AI that mimics the responses of a deceased loved one.",
    link: "/memory",
    image: Memory,
    icon: IconMemory,
  },
];

export const userData = [
  {
    image: IconMemory,
    name: "Evelyn Smith",
    banner: Banner.src,
    age: 25,
    job: "Graphic Designer",
    city: "Jakarta",
    province: "DKI Jakarta",
    nationality: "Indonesia",
    description: "Evelyn is a creative graphic designer who is passionate about transforming ideas into stunning visuals. With a strong background in both print and digital design, she loves collaborating on innovative projects that challenge her skills. She enjoys exploring new design trends and techniques to stay ahead in the industry. When she's not designing, you can find her visiting art galleries, attending workshops, or working on personal projects that allow her to express her creativity.",
    zodiak: "Libra",
    interested: ["Art", "Music", "Travel"],
    love_language: ["Quality Time", "Acts of Service"],
  },
  {
    image: IconMemory,
    name: "Andreas Kurniawan",
    banner: Banner.src,
    age: 30,
    job: "Software Engineer",
    city: "Bandung",
    province: "West Java",
    nationality: "Indonesia",
    description: "Andreas is a dedicated software engineer with a passion for creating innovative solutions to complex problems. He specializes in developing scalable web applications and has a keen interest in emerging technologies. He thrives in collaborative environments, working closely with cross-functional teams to deliver high-quality products. In his free time, Andreas enjoys contributing to open-source projects, attending tech meetups, and staying up to date with the latest advancements in software development.",
    zodiak: "Scorpio",
    interested: ["Coding", "Gaming", "Reading"],
    love_language: ["Words of Affirmation", "Physical Touch"],
  },
  {
    image: IconMemory,
    name: "Sari Pratiwi",
    banner: Banner.src,
    age: 22,
    job: "Digital Marketer",
    city: "Surabaya",
    province: "East Java",
    nationality: "Indonesia",
    description: "Sari is a digital marketer with a flair for crafting compelling campaigns that resonate with audiences. She excels in leveraging data analytics to optimize marketing strategies and enhance brand visibility. Her creativity and strategic thinking help businesses connect with their target markets effectively. In addition to her professional pursuits, Sari enjoys exploring the latest trends in social media and digital marketing. In her free time, she loves reading marketing blogs and attending industry conferences.",
    zodiak: "Aquarius",
    interested: ["Marketing", "Social Media", "Traveling"],
    love_language: ["Acts of Service", "Receiving Gifts"],
  },
  {
    image: IconMemory,
    name: "Rudi Hartono",
    banner: Banner.src,
    age: 28,
    job: "Data Scientist",
    city: "Yogyakarta",
    province: "DIY",
    nationality: "Indonesia",
    description: "Rudi is a passionate data scientist who loves uncovering insights through data analysis. His expertise lies in statistical modeling and machine learning, enabling him to drive strategic decision-making in organizations. He enjoys tackling challenging problems and finding innovative solutions that impact business outcomes. Rudi is also an advocate for data literacy and often participates in workshops and seminars to share his knowledge with others. In his spare time, he enjoys hiking and reading books on technology.",
    zodiak: "Gemini",
    interested: ["Data Analysis", "Machine Learning", "Travel"],
    love_language: ["Quality Time", "Words of Affirmation"],
  },
  {
    image: IconMemory,
    name: "Lina Setiawati",
    banner: Banner.src,
    age: 27,
    job: "Content Writer",
    city: "Bali",
    province: "Bali",
    nationality: "Indonesia",
    description: "Lina is a creative content writer who specializes in producing engaging articles and compelling narratives. She has a passion for storytelling and enjoys researching diverse topics to deliver high-quality content. Lina believes that words have the power to inspire and inform, and she takes pride in crafting content that resonates with readers. Outside of writing, she loves exploring new cultures through travel and photography, often sharing her experiences through her blog.",
    zodiak: "Pisces",
    interested: ["Writing", "Yoga", "Cooking"],
    love_language: ["Physical Touch", "Acts of Service"],
  },
  {
    image: IconMemory,
    name: "Budi Santoso",
    banner: Banner.src,
    age: 24,
    job: "Financial Analyst",
    city: "Medan",
    province: "North Sumatra",
    nationality: "Indonesia",
    description: "Budi is a detail-oriented financial analyst who is passionate about helping businesses navigate financial challenges. He specializes in budgeting, forecasting, and financial modeling, enabling organizations to make informed decisions. Budi enjoys analyzing data and identifying trends that can drive business growth. He is committed to professional development and often seeks out new learning opportunities in finance and investment. In his personal time, he enjoys playing basketball and watching documentaries.",
    zodiak: "Leo",
    interested: ["Finance", "Investing", "Sports"],
    love_language: ["Receiving Gifts", "Quality Time"],
  },
  {
    image: IconMemory,
    name: "Nina Agustin",
    banner: Banner.src,
    age: 29,
    job: "Project Manager",
    city: "Semarang",
    province: "Central Java",
    nationality: "Indonesia",
    description: "Nina is a results-driven project manager with a knack for leading teams to deliver successful projects on time and within budget. She excels at fostering collaboration and communication among team members, ensuring everyone is aligned with project goals. Nina enjoys the challenge of managing complex projects and is always looking for ways to improve processes and increase efficiency. In her free time, she loves attending workshops and learning about new project management methodologies.",
    zodiak: "Capricorn",
    interested: ["Management", "Networking", "Travel"],
    love_language: ["Acts of Service", "Words of Affirmation"],
  },
  {
    image: IconMemory,
    name: "Taufik Rahman",
    banner: Banner.src,
    age: 26,
    job: "UX/UI Designer",
    city: "Palembang",
    province: "South Sumatra",
    nationality: "Indonesia",
    description: "Taufik is a passionate UX/UI designer who is dedicated to creating user-centered designs that enhance user experiences. He believes that great design should be both beautiful and functional. Taufik thrives in collaborative environments and enjoys working with developers and product teams to bring ideas to life. Outside of work, he enjoys sketching, attending design meetups, and exploring the latest trends in user experience and interface design.",
    zodiak: "Virgo",
    interested: ["Design", "Technology", "Photography"],
    love_language: ["Quality Time", "Receiving Gifts"],
  },
  {
    image: IconMemory,
    name: "Dewi Lestari",
    banner: Banner.src,
    age: 31,
    job: "HR Specialist",
    city: "Banjarmasin",
    province: "South Kalimantan",
    nationality: "Indonesia",
    description: "Dewi is a dedicated HR specialist who is committed to enhancing workplace culture and promoting employee well-being. She excels in recruitment, training, and retention strategies, ensuring that organizations attract and retain top talent. Dewi believes in the importance of creating a supportive and inclusive work environment. In her free time, she enjoys volunteering for community service projects and participating in HR networking events to share best practices.",
    zodiak: "Aries",
    interested: ["Recruitment", "Training", "Travel"],
    love_language: ["Words of Affirmation", "Acts of Service"],
  },
  {
    image: IconMemory,
    name: "Rina Melati",
    banner: Banner.src,
    age: 23,
    job: "Web Developer",
    city: "Jakarta",
    province: "DKI Jakarta",
    nationality: "Indonesia",
    description: "Rina is an enthusiastic web developer who loves creating responsive and user-friendly websites. She is skilled in various programming languages and frameworks and is always eager to learn new technologies. Rina enjoys solving coding challenges and collaborating with designers to enhance user experiences. In her spare time, she participates in coding competitions and contributes to open-source projects, believing in the power of community in tech.",
    zodiak: "Sagittarius",
    interested: ["Programming", "Tech Meetups", "Gaming"],
    love_language: ["Physical Touch", "Quality Time"],
  },
];