import Friends from "@/assets/logo/friends.svg";
import Memory from "@/assets/logo/memory.svg";
import IconFriends from "@/assets/logo/icon_friends.svg";
import IconMemory from "@/assets/logo/icon_memory.svg";
import Banner from "@/assets/talents/banner.png";

export const projects = [
  {
    title: "Sahari Friends",
    description:
      "enjoy a safe and comfortable social experience without the risk of negative exploitation.",
    link: "/friends",
    image: Friends,
    icon: IconFriends,
  },
  {
    title: "Sahari Friends",
    description:
      "allows users to interact with an AI that mimics the responses of a deceased loved one.",
    link: "/memory",
    image: Memory,
    icon: IconMemory,
  },
];

export const userData = [
  {
    image: IconMemory,
    name: "Evelyn Smith",
    banner: Banner.src,
    age: 25,
    job: "Graphic Designer",
    city: "Jakarta",
    province: "DKI Jakarta",
    nationality: "Indonesia",
    description: "A passionate designer who loves creating stunning visuals.",
    zodiak: "Libra",
    interested: ["Art", "Music", "Travel"],
    love_language: ["Quality Time", "Acts of Service"],
  },
  {
    image: IconMemory,
    name: "Andreas Kurniawan",
    banner: Banner.src,
    age: 30,
    job: "Software Engineer",
    city: "Bandung",
    province: "West Java",
    nationality: "Indonesia",
    description: "A tech enthusiast who enjoys solving complex problems.",
    zodiak: "Scorpio",
    interested: ["Coding", "Gaming", "Reading"],
    love_language: ["Words of Affirmation", "Physical Touch"],
  },
  {
    image: IconMemory,
    name: "Sari Pratiwi",
    banner: Banner.src,
    age: 22,
    job: "Digital Marketer",
    city: "Surabaya",
    province: "East Java",
    nationality: "Indonesia",
    description: "Loves connecting brands with their audience through effective marketing.",
    zodiak: "Aquarius",
    interested: ["Marketing", "Social Media", "Traveling"],
    love_language: ["Acts of Service", "Receiving Gifts"],
  },
  {
    image: IconMemory,
    name: "Rudi Hartono",
    banner: Banner.src,
    age: 28,
    job: "Data Scientist",
    city: "Yogyakarta",
    province: "DIY",
    nationality: "Indonesia",
    description: "Enjoys uncovering insights from data to drive business decisions.",
    zodiak: "Gemini",
    interested: ["Data Analysis", "Machine Learning", "Travel"],
    love_language: ["Quality Time", "Words of Affirmation"],
  },
  {
    image: IconMemory,
    name: "Lina Setiawati",
    banner: Banner.src,
    age: 27,
    job: "Content Writer",
    city: "Bali",
    province: "Bali",
    nationality: "Indonesia",
    description: "A creative writer who tells compelling stories.",
    zodiak: "Pisces",
    interested: ["Writing", "Yoga", "Cooking"],
    love_language: ["Physical Touch", "Acts of Service"],
  },
  {
    image: IconMemory,
    name: "Budi Santoso",
    banner: Banner.src,
    age: 24,
    job: "Financial Analyst",
    city: "Medan",
    province: "North Sumatra",
    nationality: "Indonesia",
    description: "Focused on helping businesses achieve financial success.",
    zodiak: "Leo",
    interested: ["Finance", "Investing", "Sports"],
    love_language: ["Receiving Gifts", "Quality Time"],
  },
  {
    image: IconMemory,
    name: "Nina Agustin",
    banner: Banner.src,
    age: 29,
    job: "Project Manager",
    city: "Semarang",
    province: "Central Java",
    nationality: "Indonesia",
    description: "Skilled in leading teams to achieve project goals efficiently.",
    zodiak: "Capricorn",
    interested: ["Management", "Networking", "Travel"],
    love_language: ["Acts of Service", "Words of Affirmation"],
  },
  {
    image: IconMemory,
    name: "Taufik Rahman",
    banner: Banner.src,
    age: 26,
    job: "UX/UI Designer",
    city: "Palembang",
    province: "South Sumatra",
    nationality: "Indonesia",
    description: "Passionate about creating user-friendly interfaces.",
    zodiak: "Virgo",
    interested: ["Design", "Technology", "Photography"],
    love_language: ["Quality Time", "Receiving Gifts"],
  },
  {
    image: IconMemory,
    name: "Dewi Lestari",
    banner: Banner.src,
    age: 31,
    job: "HR Specialist",
    city: "Banjarmasin",
    province: "South Kalimantan",
    nationality: "Indonesia",
    description: "Dedicated to improving workplace culture and employee well-being.",
    zodiak: "Aries",
    interested: ["Recruitment", "Training", "Travel"],
    love_language: ["Words of Affirmation", "Acts of Service"],
  },
  {
    image: IconMemory,
    name: "Rina Melati",
    banner: Banner.src,
    age: 23,
    job: "Web Developer",
    city: "Jakarta",
    province: "DKI Jakarta",
    nationality: "Indonesia",
    description: "Enthusiastic coder who loves building responsive websites.",
    zodiak: "Sagittarius",
    interested: ["Programming", "Tech Meetups", "Gaming"],
    love_language: ["Physical Touch", "Quality Time"],
  },
];